@startuml
set namespaceSeparator ::

class "iitropar::views::PBTabView::MainLandingPage" {
  int _selectedIndex
  initState()
  dispose()
  _onPageChanged()
  _onItemTapped()
  _buildScreens()
  _navbarItems()
  _getSelectedItemColor()
}

@enduml