@startuml
set namespaceSeparator ::

class "iitropar::database::event::Event" {
  String title
  String desc
  String creator
  String venue
  String host
  int h
  String s
  int hour
  int min
  startTime()
  endTime()
  displayTime()
  compareTo()
  _convertTo12()
  tod2str()
  str2tod()
}

@enduml