@startuml
set namespaceSeparator ::

class "iitropar::views::faculty::seeSlots::ConflictSlot" {
  int conflicts
}

class "iitropar::views::faculty::seeSlots::seeSlots" {
  int slotLength
  List<int> conflicts
}

class "iitropar::views::faculty::seeSlots::GradientColorGenerator" {
  int max
  double percentage
  int red
  int green
  int slotLength
  List<int> conflicts
  int totalSlots
  {static} +Color getColorFromGradient()
  createSlotCard()
  _slotDetail()
  viewSlots()
  build()
}

@enduml