@startuml
set namespaceSeparator ::

class "iitropar::views::club::group_members::groupMembersScreen" {
  String groupName
  String groupName
  build()
}

class "iitropar::views::club::group_members::GroupList" {
  String groupName
  String groupName
  List<DocumentSnapshot> members
  String documentId
  Map<String, dynamic> data
  build()
}

@enduml