@startuml
set namespaceSeparator ::

class "iitropar::views::admin::update_timetable::updateTimetablecsv" {
  String fileName
  verifyHeader()
  build()
  themeButtonWidget()
  appbarTitleStyle()
  buildTitleBar()
}

@enduml