@startuml
set namespaceSeparator ::

class "iitropar::views::admin::update_end_sem_schedule::updateEndSemSchedule" {
  String fileName
  build()
  themeButtonWidget()
  appbarTitleStyle()
  buildTitleBar()
}

@enduml