@startuml
set namespaceSeparator ::

class "iitropar::database::loader::Loader" {
  int hour
  int min
  String decodedData
  List<String> lines
  String decodedData
  int len
  String course
  String classVenue
  String tutorialVenue
  String decodedData
  List<String> timings
  List<String> tokens
  int sz
  String weekday
  String slot
  String title
  String host
  String desc
  String day
  int mask
  String stime
  String etime
  String venue
  String decodedData
  List<List<dynamic>> exams
  Map<String, String> slotToDay
  List<String> slot1_courses
  List<String> slot2_courses
  List<String> slot3_courses
  String decodedData
  Map<String, String> slotToDay
  List<String> courses1
  List<String> courses2
  List<ExtraClass> extras
  List<ExtraClass> labs
  String role
  List<ExtraClass> labs
  {static} +String convertTo24()
}

@enduml