@startuml
set namespaceSeparator ::

class "iitropar::views::faculty::findSlot::findSlots" {
  int slotLength
  bool inputFormat
  Map<String, String> entryToName
  String header
  String entryNumber
  String filePath
  List<dynamic> studentList
  List<int> conflicts
  int diff
  String day
  int from
  int to
  int slotStart
  int slotEnd
  int idx
  List<ExtraClass> lec
  int from
  int to
  int slotStart
  int slotEnd
  int idx
  verifyHeader()
  addSingleStudent()
  getCSVscreen()
  selectCourses()
  getStudents()
  showSelectedStudents()
  getSlot()
  getDate()
  submitButton()
  build()
}

@enduml