@startuml
set namespaceSeparator ::

class "iitropar::views::club::club_notifications::ClubNotifications" {
  String clubName
  String clubName
  build()
}

class "iitropar::views::club::club_notifications::NotificationsList" {
  String clubName
  String clubName
  Map<String, dynamic> notifications
  List<List<Map<String, dynamic>>> notificationsList
  initState()
  _fetchNotifications()
  build()
}

@enduml