@startuml
set namespaceSeparator ::

class "iitropar::utilities::firebase_database::firebaseDatabase" {
  String createdAt
  int len
  List<dynamic> group_events
  int len
  List<dynamic> students
  List<dynamic> courses
  int len
  List<List<dynamic>> students
  List<dynamic> courses
  String docName
  Map<String, String> holiday
  List<holidays> hols
  String docName
  String docName
  String docName
  List<changedDay> changedDays
  Map<String, dynamic> crs
  List<String> details
  List<faculty> fc
  bool hasCourses
  List<String> courses
  List<Event> events
  String doc_eventDate0
  List<String> date_split
  List<String> cc
  List<DateTime> dts
  List<ExtraClass> ec
  String description
  String venue
  List<ExtraClass> ec
  List<String> groups
  int targetWeekday
  List<String> collections
  List<String> courses
  Map<String, String> mp
  List<String> emailIds
  Map<String,dynamic> details
  String sentTime
  Map<String, Map<String, dynamic>> fullMenu
  List<dynamic> currentGroups
  {static} +void addEventFB()
  {static} +void addClubEvent()
  {static} +void updateFaculty()
  {static} +void addHolidayFB()
  {static} +void switchTimetableFB()
  {static} +void deleteChDay()
  {static} +void deleteHol()
  {static} +void addCourseFB()
  {static} +void registerFacultyFB()
  {static} +void registerClubFB()
  {static} +void addCourseCode()
  {static} +void deleteClass()
  {static} +void addSemDur()
  {static} +void addClubGroup()
  {static} +void modifyClubGroup()
  {static} +void addClubMembers()
  {static} +void addNotification()
  {static} +void updateMenu()
  weekdayFromString()
}

@enduml