@startuml
set namespaceSeparator ::

class "iitropar::views::admin::add_event::AddEvent" {
  build()
  themeButtonWidget()
  appbarTitleStyle()
  buildTitleBar()
}

class "iitropar::views::admin::add_event::AddEventForm" {
  String filename
  String filePath
  createState()
  formatTimeOfDay()
  _buildEventTitle()
  _buildEventType()
  _buildEventDesc()
  _buildEventVenue()
  _buildEventDate()
  _buildStartTime()
  _buildEndTime()
}

@enduml