@startuml
set namespaceSeparator ::

class "iitropar::database::local_db::EventDB" {
  String datestr
  List<Event> allEvents
  Map<String, Event> uniqueEvents
  String key
  List<Event> finalList
  int ans
  {static} +bool firstRun()
  _convertToEvent()
  _getID()
}

@enduml