@startuml
set namespaceSeparator ::

class "iitropar::frequently_used::holidays" {
}

class "iitropar::frequently_used::semesterDur" {
}

class "iitropar::frequently_used::changedDay" {
}

class "iitropar::frequently_used::faculty" {
}

class "iitropar::frequently_used::Ids" {
  String user
  String check1
}

class "iitropar::frequently_used::MenuItem" {
  String name
  String description
}

class "iitropar::frequently_used::Menu" {
  Map<String, Map<String, dynamic>> fetchedMenu
  Map<String, List<MenuItem>> tempMenu
  AdminCard()
}

class "iitropar::frequently_used::LoadingScreen" {
  {static} +void setPrompt()
  {static} +Widget build()
  signoutButtonWidget()
}

class "iitropar::frequently_used::ExtraClass" {
  String venue
  String description
  String courseID
}

class "iitropar::frequently_used::formChecks" {
  {static} +bool isbeforeDate()
  {static} +bool beforeCurDate()
  {static} +bool email_check()
  formatDateWord()
}

@enduml