@startuml
set namespaceSeparator ::

class "iitropar::views::club::add_group::addClubGroup" {
  String clubName
  String clubName
  build()
}

class "iitropar::views::club::add_group::AddClubForm" {
  String clubName
  String clubName
  String dropdownValue
  createState()
  _buildGroupName()
  _buildGroupDesc()
}

@enduml